Update test.yml
Add fortify scan job template code

diff --git a/test.yml b/test.yml
--- a/test.yml
+++ b/test.yml
@@ -23,3 +23,55 @@ git push origin feature-generateCI
 zip -r my-backup.zip . -x "*.git/*"
 
 tar -czvf my-backup.tar.gz --exclude='.git' .
+
+
+.fortify_scan_updated:
+  image: artifactory.jfrog.sbi:443/dso-base-image/ubi9/ubi9-java17-fortify-24.4:2.0
+  rules:
+    - if: '( $CI_PIPELINE_SOURCE == "parent_pipeline" && $CI_COMMIT_REF_NAME =~ /^feature-/ ) || ( $CI_PIPELINE_SOURCE == "parent_pipeline" && $CI_COMMIT_REF_NAME =~ /^hotfix-/ ) || ( $CI_PIPELINE_SOURCE == "parent_pipeline" && $CI_COMMIT_BRANCH == "dev" )'
+      changes:
+        - "$APP_DIR/**"
+        - "$APP_DIR/**/*"
+  variables:
+    MAVEN_OPTS: "-Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
+    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DskipTests"
+  before_script:
+    - |
+      cd "$APP_DIR" 
+      keytool -import -alias jfrog-artifactory -file "$ARTIFACTORY_CERT" \
+        -keystore /home/default/custom-truststore.jks -storepass changeit -noprompt
+      export MAVEN_OPTS="${MAVEN_OPTS} \
+        -Djavax.net.ssl.trustStore=/home/default/custom-truststore.jks \
+        -Djavax.net.ssl.trustStorePassword=changeit"
+  script:
+    - sourceanalyzer -clean -b $APP_NAME
+    - sourceanalyzer -b $APP_NAME
+        mvn $MAVEN_CLI_OPTS clean compile -U -DskipTests=true
+        -Dfortify.sca.exclude=target
+    - sourceanalyzer -b $APP_NAME -scan -Xmx8G -filter $CI_PROJECT_DIR/fortify_filter.txt -f ${APP_NAME}.fpr
+    - BIRTReportGenerator -template "Developer Workbook"
+        -source ${APP_NAME}.fpr
+        -format pdf -output ${APP_NAME}_report.pdf
+    - FPRUtility -information -search
+        -query "[fortify priority order]:critical OR [fortify priority order]:high OR [fortify priority order]:medium OR [fortify priority order]:low"
+        -project ${APP_NAME}.fpr > sca_gate.txt
+    - ISSUES=$(grep -i "matched search query" sca_gate.txt | awk '{print $1}')
+    - |
+      if [ -n "$ISSUES" ] && [ "$ISSUES" -gt 0 ]; then
+        echo -e "\e[31m=========================================\e[0m"
+        echo -e "\e[31m QUALITY GATE FAILED\e[0m"
+        echo -e "\e[31mHigh/Critical Vulnerabilities: $ISSUES\e[0m"
+        echo -e "\e[31m=========================================\e[0m"
+        exit 1
+      else
+        echo -e "\e[32m=========================================\e[0m"
+        echo -e "\e[32m QUALITY GATE PASSED\e[0m"
+        echo -e "\e[32mHigh/Critical Vulnerabilities: 0\e[0m"
+        echo -e "\e[32m=========================================\e[0m"
+      fi
+  artifacts:
+    paths:
+      - "$APP_DIR/${APP_NAME}_report.pdf"
+      - "$APP_DIR/${APP_NAME}.fpr"
+    expire_in: 1 day
+    when: always
